"""Remembers which photos are already on the frame, by content.

An album sync that runs on a schedule cannot tell the frame anything useful
about identity. The iPhone Shortcut that watches an album asks for "photos
added in the last day" and posts them; run it daily and every photo is offered
at least once more than necessary, run it hourly and each one arrives twenty
times. Nothing in a multipart upload distinguishes the second copy from the
first — the filename is regenerated by Photos, and the bytes are re-encoded on
export, so even the size can move.

So identity is the bytes as they arrive. A photo is the same photo if the file
posted is byte-for-byte the file posted before, which is exactly true for a
repeated export of an unedited photo and false as soon as somebody crops it —
which is the behaviour wanted in both cases.

The index is a sidecar next to the photos rather than a database: it is a
cache, and losing it costs one duplicate per photo, not a broken frame.
"""

import hashlib
import json
import logging
import os
import tempfile

logger = logging.getLogger("vignette.photo_ledger")

INDEX_NAME = ".upload-index.json"

# One photo from a modern phone is a few megabytes; a frame holds hundreds.
# The index is read and written whole, so it is capped — the oldest entries
# fall off and at worst a very old photo can be uploaded twice.
MAX_ENTRIES = 4000

_CHUNK = 1024 * 1024


def digest_file(path):
    """SHA-256 of a file on disk, read in chunks so a large photo is not
    loaded into memory on a Pi Zero."""
    hasher = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(_CHUNK), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


class PhotoLedger:
    """content hash -> the filename it was stored as."""

    def __init__(self, output_dir):
        self.output_dir = output_dir
        self.path = os.path.join(output_dir, INDEX_NAME)
        self._entries = {}
        self.load()

    def load(self):
        try:
            with open(self.path, "r", encoding="utf-8") as handle:
                data = json.load(handle)
            if isinstance(data, dict):
                self._entries = {k: v for k, v in data.items()
                                 if isinstance(k, str) and isinstance(v, str)}
        except FileNotFoundError:
            self._entries = {}
        except Exception as exc:  # noqa: BLE001 - a corrupt cache is not fatal
            logger.warning("Upload index unreadable (%s); starting a new one", exc)
            self._entries = {}

    def save(self):
        if len(self._entries) > MAX_ENTRIES:
            # dicts keep insertion order, so this drops the oldest.
            excess = len(self._entries) - MAX_ENTRIES
            for key in list(self._entries)[:excess]:
                del self._entries[key]
        try:
            fd, staging = tempfile.mkstemp(dir=self.output_dir, prefix=".index-")
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                json.dump(self._entries, handle)
            os.replace(staging, self.path)
        except Exception as exc:  # noqa: BLE001 - the cache is not worth failing an upload
            logger.warning("Could not write the upload index: %s", exc)

    def lookup(self, digest):
        """The filename this content was stored as, if it is still there.

        A photo deleted from the gallery must be uploadable again, so an entry
        whose file has gone is dropped rather than reported as a duplicate.
        """
        name = self._entries.get(digest)
        if not name:
            return None
        if not os.path.isfile(os.path.join(self.output_dir, name)):
            del self._entries[digest]
            self.save()
            return None
        return name

    def remember(self, digest, filename):
        # Re-inserted at the end so the cap above drops genuinely old entries.
        self._entries.pop(digest, None)
        self._entries[digest] = filename
        self.save()

    def forget_missing(self):
        """Drop entries whose photo is no longer in the gallery."""
        gone = [d for d, name in self._entries.items()
                if not os.path.isfile(os.path.join(self.output_dir, name))]
        for digest in gone:
            del self._entries[digest]
        if gone:
            self.save()
        return len(gone)
